### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by farzonl** [jscert/jscert#9]
Is there an effort planned to start work on the new spec?

**Comment by IgnoredAmbience** [comment]
Yes, but with a different approach. Rather than producing both the operational semantics and reference interpreter and proof to join them, we're investigating methods to write only one of these and automatically generate the others.
Proof of concept work towards this is in progress in the es2016-proxies branch of the jscert/jsexplain repository.

**Comment by farzonl** [comment]
Cool thanks for the info. I'll take a look!

**Comment by IgnoredAmbience** [comment]
Will add that development on there has recently stalled due to other projects, but hope to resume it shortly. The code there is definitely not trustworthy yet, as we're yet to do any serious testing/evaluation of the approach. Ideally we'd be able to produce something like the full extent of the jscert project from the sorts of specifications being researched there.
